### PR TITLE
better checking for file existance, access to file, etc; closes #11

### LINKED ISSUE #11: private files downloadable without credentials?
On Windows, s3_get() produces the error:
```
> test1<-s3_get("s3://geomarker/testing_downloads/mtcars.rds")
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden
```
This happens for public and private files. Using the same setup on MacOS works properly with no errors.

### PR DESCRIPTION
**Pull request by erikarasnick**
accidentally commited some changes to master before this

### CODE REVIEW

**Review by cole-brokamp — CHANGES_REQUESTED** [review]
I like this approach!  Can we also add some accompanying tests that verify the different possible outcomes with respect to downloading files without access, downloading files that don't exist, downloading a bunch of files when some of them already exist, etc...?

**Comment by cole-brokamp** [comment]
I like the `s3_check_file` function, but I've separated it into two different functions so that we can use them more easily within the other functions.  They each return a logical, but will also emit messages if wanted too.  

I haven't yet updated the `s3_get_files` function to utilize these functions (but I did update `s3_get`.  Wanted to get it up here in case you want to work on it.  I want to work on it later today and hopefully will get back to it soon.

**Comment by cole-brokamp** [comment]
Also, I'm still having problems with testing for the private downloads 🤷‍♂️ . We will get back to that soon.

**Comment by erikarasnick** [comment]
If I have fake credentials set, I can't even download a public file. I get this warning for both public and private

Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden

Detailed traceback: 
  File "/Users/RASV5G/Library/r-miniconda/envs/r-s3/lib/python3.9/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/RASV5G/Library/r-miniconda/envs/r-s3/lib/python3.9/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)

 I don't think boto head_object function works at all if you don't have credentials.

**Comment by cole-brokamp** [comment]
You're right.  We should never be using the boto methods without credentials. I think public files still require valid aws credentials to download through boto, so we use httr stuff instead.  I think it would be right to get an error when trying to download a public file if you have invalid credentials.

We could write a fallback so that if a file errors to download when using credentials, it also attempts to download it via the public / "httr" stuff, but I'm not sure how often that case would come up.

**Comment by erikarasnick** [comment]
Oh, right. Got too deep in checking scenarios haha. I was mostly thinking if a DeGAUSS user was trying to download private files but their aws account hadn't been given access to the files for some reason. 

I also don't get an error now when I run the last test with the "fake" credentials.

**Comment by cole-brokamp** [comment]
That's a good point.  I'm not sure if there is a way to differentiate between "this file doesn't exist" and "you don't have permission to access this file".  We might have to be very careful when we do use private data in a DeGAUSS container by sending the user a message saying that it could fail if they don't have proper AWS permissions set.

**Comment by erikarasnick** [comment]
That would work. Another maybe not very probable scenario... Do you think we would ever have the case where someone without credentials would be trying to download multiple files with s3_get_files and some were private and some not?

**Comment by cole-brokamp** [comment]
What command do you use to render the README.Rmd into a README.md?  I'm getting some weird output with the `cli` icons when I try to do this.

**Comment by erikarasnick** [comment]
I usually just use the knit button in Rstudio.

**Comment by cole-brokamp** [comment]
I'm not in R Studio, but its showing weird unicode characters for me when I try `rmarkdown::render()` or `knitr::knit()`.  Can you push up the rendered README here and I will merge and do a new release?

**Pull request merged**
